### PR TITLE
Use MooseModel visitor instead of #isKindOf: and if.

### PR DESCRIPTION
**Pull request by jecisc**
This is some improvements made by Usman.

### CODE REVIEW

**Comment by peteruhnak** [comment]
Strange that no tests were ran on CI (should be 47, not 0)

**Comment by jecisc** [comment]
This is strange indeed. Thank you for the collaboration invit.

**Comment by peteruhnak** [comment]
Hmm, even after merge it didn't detect any tests. Maybe an old configuration; I'll take a look later (unless you resolve it in the meantime)

**Comment by jecisc** [comment]
I'm afraid I'll not have the time soon :( A lot of work to do right now.

**Comment by peteruhnak** [comment]
No worries.

**Pull request merged**
