### PR TITLE
Migrate XMI-Analyzer to Moose 8

### PR DESCRIPTION
**Pull request by jecisc**
Migrate XMI-Analyzer to Moose 8.

- Add Iceberg metadatas
- Migrate repo to Tonel
- Update CI to build on Pharo 8 an 9 (allowed failure for the latter)
- Depend on xml-dom-visitor on OpenPonk
- Split tests in their own package
- Depend on Famix of Moose 8 instead of Moose 6.1
- Since in Moose 8 we have multiple MM, ask for a factory to build the Moose instances
- Add methods that where removed from Moose 8 (visiting methods)
- Create a new MM for the tests and use it

### CODE REVIEW

**Comment by jecisc** [comment]
@peteruhnak Do you agree to merge this PR?

Maybe we should do a release before if someone want to depend on the Moose 6.1 version?

**Comment by peteruhnak** [comment]
Hi @jecisc , I think it would make more sense to:

* fork this repo under https://github.com/moosetechnology
* I'll update the readme that this repo is not maintained and direct people to that fork

**Comment by jecisc** [comment]
https://github.com/moosetechnology/xmi-analyzer

**Comment by peteruhnak** [comment]
Thanks, I've updated the README.

**Pull request closed without merging**
